comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
ignore:
  - **/*_gen.go
  - **/*_test.go
  - **/doc.go
  - **/testdata
  - internal/adapter/gql/generated.go
  - tools
  - main.go
  - tools.go
