name: build
on:
  workflow_run:
    workflows: [ci]
    type: [completed]
    branches: [main, release]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true
jobs:
  info:
    name: Collect information
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.repository.full_name == 'reearth/reearth-backend' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'release')
    outputs:
      sha_short: ${{ steps.info.outputs.sha_short }}
      tag: ${{ steps.info.outputs.tag }}
      tag_short: ${{ steps.info.outputs.tag_short }}
      name: ${{ steps.info.outputs.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Get info
        id: info
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        # The tag name should be retrieved lazily, as tagging may be delayed.
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          TAG=$(git tag --points-at HEAD)
          if [[ ! -z "$TAG" ]]; then
            echo "::set-output name=tag::$TAG"
            echo "::set-output name=tag_short::${TAG#v}"
          fi
          if [[ "$BRANCH" = "release" ]]; then
            echo "::set-output name=name::rc"
          else
            echo "::set-output name=name::nightly"
          fi
      - name: Show info
        env:
          SHA_SHORT: ${{ steps.info.outputs.sha_short }}
          TAG: ${{ steps.info.outputs.tag }}
          TAG_SHORT: ${{ steps.info.outputs.tag_short }}
          NAME: ${{ steps.info.outputs.name }}
        run: echo "sha_short=$SHA_SHORT, tag=$TAG, tag_short=$TAG_SHORT, name=$NAME"
  build:
    name: Build and release
    runs-on: ubuntu-latest
    needs:
      - info
    env:
      ARTIFACTS: dist/reearth-backend_*.*
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --snapshot
        env:
          GORELEASER_CURRENT_TAG: ${{ needs.info.outputs.tag || '0.0.0' }}
      - name: Rename artifacts
        if: "!needs.info.outputs.tag"
        run: for f in $ARTIFACTS; do mv $f $(echo $f | sed -E 's/_0\.0\.0-SNAPSHOT-[^_]*/_${{ needs.info.outputs.name }}/'); done
      - name: Release nightly/rc
        if: "!needs.info.outputs.tag"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ env.ARTIFACTS }}
          commit: ${{ github.sha }}
          name: ${{ needs.info.outputs.name }}
          tag: ${{ needs.info.outputs.name }}
          body: ${{ github.sha }}
          prerelease: true
      - name: Download latest changelog
        if: github.event.workflow_run.head_branch == 'release' && needs.info.outputs.tag
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          name: changelog-${{ needs.info.outputs.tag }}
      - name: Create GitHub release
        if: github.event.workflow_run.head_branch == 'release' && needs.info.outputs.tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ARTIFACTS }}
          commit: ${{ github.sha }}
          name: ${{ needs.info.outputs.tag }}
          tag: ${{ needs.info.outputs.tag }}
          bodyFile: CHANGELOG_latest.md
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs:
      - info
    env:
      IMAGE_NAME: reearth/reearth-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get options
        id: options
        env:
          TAG: ${{ needs.info.outputs.tag_short }}
          NAME: ${{ needs.info.outputs.name }}
          SHA: ${{ needs.info.outputs.sha_short }}
        run: |
          if [[ -n $TAG ]]; then
            PLATFORMS=linux/amd64,linux/arm64
            VERSION=$TAG
            TAGS=$IMAGE_NAME:$TAG
            if [[ ! $TAG =~ '-' ]]; then
              TAGS+=,${IMAGE_NAME}:${TAG%.*}
              TAGS+=,${IMAGE_NAME}:${TAG%%.*}
              TAGS+=,${IMAGE_NAME}:latest
            fi
          else
            PLATFORMS=linux/amd64
            VERSION=$SHA
            TAGS=$IMAGE_NAME:$NAME
          fi
          echo "::set-output name=platforms::$PLATFORMS"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tags::$TAGS"
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ steps.options.outputs.platforms }}
          push: true
          build-args: VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Invoke deploy_test workflow
        uses: benc-uk/workflow-dispatch@v1
        if: needs.info.outputs.name == 'nightly'
        with:
          workflow: deploy_test
          token: ${{ secrets.GPT }}
