name: nightly
on:
  workflow_run:
    workflows:
      - main
    types:
      - completed
jobs:
  nightly:
    name: nightly
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o reearth-backend -tags "release" "-ldflags=-X main.version=nightly -s -buildid=" -trimpath ./cmd/reearth
      - name: Package
        run: tar -zcvf reearth-backend_linux_amd64.tar.gz reearth-backend
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: reearth-backend_*.tar.gz
          artifactContentType: application/gzip
          commit: ${{ env.GITHUB_SHA }}
          name: Nightly release
          prerelease: true
          tag: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
  nightly_docker:
    name: nightly_docker
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=nightly
          tags: reearth/reearth-backend:nightly
          cache-from: type=registry,ref=reearth/reearth-backend:nightly
          cache-to: type=inline
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  slack-notification:
    if: always()
    name: Slack Notification
    needs:
      - nightly
      - nightly_docker
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
