name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Next version (NOTE: Switch the branch to "release"!)'
        type: choice
        default: minor
        options:
          - patch
          - minor
          - major
  pull_request: # debug
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/release'
    steps:
      - name: Set up git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GPT }}
      - id: changelog
        name: Generate CHANGELOG
        uses: reearth/changelog-action@main
        with:
          version: ${{ github.event.inputs.version }}
          repo: ${{ github.repository }}
          latest: true
      - run: git diff # debug
      # - name: Upload latest CHANGELOG
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: changelog-${{ steps.tag.outputs.new_tag }}
      #     path: CHANGELOG_latest.md
      # - name: Commit & push
      #   env:
      #     TAG: ${{ steps.tag.outputs.new_tag }}
      #   run: |
      #     rm CHANGELOG_latest.md
      #     git add CHANGELOG.md
      #     git commit -am "$TAG"
      #     git tag $TAG
      #     git push
      #     git push --tags
